version: "3.8"

services:
  db:
    image: mysql
    container_name: db_drive_it
    restart: always
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    networks:
      - dev

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin_drive_it
    restart: always
    depends_on:
      - db
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
    networks:
      - dev

  www:
    build: docker
    container_name: www_drive_it
    ports:
      - "8741:80"
    volumes:
      - ./vhosts:/etc/apache2/sites-enabled
      - ./:/var/www
    restart: always
    networks:
      - dev

networks:
  dev:

volumes:
  db-data:
